# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: warning
  logs:
    feeding: info
    feeding_api: debug
    pools_plc: info
    homeassistant.helpers.entity: debug

lovelace:
  mode: yaml
  resources:
  - url: /local/upload-csv-card.js
    type: module
  - url: /local/button-card.js
    type: module

feeding_plc:
  - host: 192.168.14.17
    number: 1
    pool_plc_index: 1
    fry: true
  - host: 192.168.14.17
    number: 2
    pool_plc_index: 2
    fry: true
  - host: 192.168.14.17
    number: 3
    pool_plc_index: 3
    fry: true
  - host: 192.168.14.17
    number: 4
    pool_plc_index: 4
    fry: true
  - host: 192.168.14.17
    number: 5
    pool_plc_index: 5
    fry: true
  - host: 192.168.14.17
    number: 6
    pool_plc_index: 6
    fry: true
  - host: 192.168.14.17
    number: 7
    pool_plc_index: 7
    fry: true
  - host: 192.168.14.17
    number: 8
    pool_plc_index: 8
    fry: true
  - host: 192.168.14.17
    number: 9
    pool_plc_index: 9
    fry: true
  - host: 192.168.14.17
    number: 10
    pool_plc_index: 10
    fry: true
  - host: 192.168.14.18
    number: 11
    pool_plc_index: 1
    fry: true
  - host: 192.168.14.18
    number: 12
    pool_plc_index: 2
    fry: true
  - host: 192.168.14.18
    number: 13
    pool_plc_index: 3
    fry: true
  - host: 192.168.14.18
    number: 14
    pool_plc_index: 4
    fry: true
  - host: 192.168.14.18
    number: 15
    pool_plc_index: 5
    fry: true
  - host: 192.168.14.18
    number: 16
    pool_plc_index: 6
    fry: true
  - host: 192.168.14.18
    number: 17
    pool_plc_index: 7
    fry: true
  - host: 192.168.14.18
    number: 18
    pool_plc_index: 8
    fry: true
  - host: 192.168.14.18
    number: 19
    pool_plc_index: 9
    fry: true
  - host: 192.168.14.18
    number: 20
    pool_plc_index: 10
    fry: true

pools_plc:
  - host: 192.168.14.17
    number: 1
    fry: true
  - host: 192.168.14.18
    number: 2
    fry: true
    extra_sensors: true

recorder:
  exclude:
    entity_globs:
      - sensor.b*_sled_korm_1
      - sensor.b*_sled_korm_2
      - sensor.sh*_vremia

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_token
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id
